image: maven:3-openjdk-17

before_script:
  - echo '<settings
          xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
          https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <mirrors>
              <mirror>
                <id>ensisa</id>
                <name>Nexus ENSISA</name>
                <url>https://nexus.cluster.ensisa.uha.fr/repository/maven-public/</url>
                <mirrorOf>*</mirrorOf>
              </mirror>
            </mirrors>
          </settings>' > settings.xml

variables:
  MAVEN_CLI_OPTS: "--batch-mode -s settings.xml -Dmaven.repo.local=libs"

cache:
  paths:
    - "libs"
    - "**/target"

stages:
  - compile
  - start_containers
  - integration_tests

compile:
  stage: compile
  script:
    - mvn clean compile


start_containers:
  stage: start_containers
  image: docker
  variables:
    DOCKER_HOST: "tcp://dind:2375"
  script:
    - docker stop $(docker ps -a -q) || /bin/true
    - docker rm $(docker ps -a -q) || /bin/true
    - docker volume create data-volume
    - docker create -v data-volume:/ext_config --name helper busybox true
    - docker cp ./ext_config helper:/ext_config
    - docker compose up -d --build
    - docker rm helper
    - proxy_id=$(docker ps -aqf "name=.*proxy.*")
    - app_id=$(docker ps -aqf "name=.*app.*")
    - db_id=$(docker ps -aqf "name=.*db.*")
    - echo "$proxy_id" > containers_id
    - echo "$app_id" >> containers_id
    - echo "$db_id" >> containers_id

integration_tests:
  stage: integration_tests
  image: maven:3-jdk-8
  script:
  #  - microdnf install wget
  #  - microdnf install unzip
  #  - microdnf install hostname
    - wget https://nexus.cluster.ensisa.uha.fr/repository/maven-public/io/gatling/highcharts/gatling-charts-highcharts-bundle/3.9.5/gatling-charts-highcharts-bundle-3.9.5-bundle.zip
    - unzip gatling-charts-highcharts-bundle-3.9.5-bundle.zip
    - export GATLING_HOME=$(cd gatling-charts-highcharts-bundle-3.9.5; pwd)
    - export DOCKER_HOST="tcp://dind:2375"
    - export POD_IP=$(hostname -I)
    - export NGINX_PROXY_ID=$(seq '1q;d' containers_id)
    - mkdir -p it/src; cd it
    - cp ../pom.xml ; sed -i 'java.version/d' pom.xml
    - cp -r ../src/test ./src/
    - mvn $MAVEN_CLI_OPTS verify