image: maven:3-eclipse-temurin-17

before_script:
  - echo '<settings
          xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
          https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <mirrors>
              <mirror>
                <id>ensisa</id>
                <name>Nexus ENSISA</name>
                <url>https://nexus.cluster.ensisa.uha.fr/repository/maven-public/</url>
                <mirrorOf>*</mirrorOf>
              </mirror>
            </mirrors>
          </settings>' > settings.xml

variables:
  MAVEN_CLI_OPTS: "--batch-mode --no-transfer-progress -U -s settings.xml"
  DOCKER_HOST: $DOCKER_REMOTE_HOST

start_containers:
  image: docker
  script:
    - cd anti-demo
    # Wait until docker server is free from other similar tasks
    - while [ "1" -eq $(docker ps -qa -f name="helper" | wc -l) ]; do echo "Waiting for docker host to be free (use 'manual_stop_containers' job to force)"; docker ps -a; sleep 5; done
    - docker create -v `pwd`/ext_config:/ext_config --name helper -it busybox /bin/sh
    - docker cp ./ext_config helper:/ # transmitting . for remote docker compose
    - docker compose up -d --build
    - docker ps -a


resources_test:
  needs:
    - start_containers
  variables:
    GATLING_VERSION: "3.9.5"
  script:
  - cd testbench
  - apt-get update; apt-get install -y wget unzip
  - wget -q https://nexus.cluster.ensisa.uha.fr/repository/maven-public/io/gatling/highcharts/gatling-charts-highcharts-bundle/$GATLING_VERSION/gatling-charts-highcharts-bundle-$GATLING_VERSION-bundle.zip
  - unzip -q gatling-charts-highcharts-bundle-$GATLING_VERSION-bundle.zip
  - export GATLING_HOME=$(cd gatling-charts-highcharts-bundle-$GATLING_VERSION; pwd)
  - cp ../settings.xml settings.xml
  - mvn $MAVEN_CLI_OPTS clean
  - mvn -U $MAVEN_CLI_OPTS verify
  artifacts:
    paths:
    - "**/target/ecoconception/*"
    reports:
      junit:
      - "**/target/surefire-reports/TEST-*.xml"
      metrics:
        - "**/target/ecoconception/*/metrics.prom"

.stop_containers: &stop_containers
  image: docker
  script:
    - cd anti-demo
    - docker compose down -v || /bin/true
    - docker rm helper || /bin/true
    - docker ps -a

cleanup_containers:
  <<: *stop_containers
  needs:
    - start_containers
    - resources_test
  rules:
    - when: always

manual_stop_containers:
  <<: *stop_containers
  rules:
    - when: manual

list_containers:
  image: docker
  script:
    - docker ps -a
  when: manual
